FROM python:3.12-slim@sha256:cab2dbf575e971934a81e4622f5aba17aa7929719bd7e31033a3a83b97fd0464
WORKDIR /app
COPY requirements.docx-sandbox.txt .
RUN pip install --no-cache-dir -r requirements.docx-sandbox.txt
COPY docx_sandbox docx_sandbox
CMD ["uvicorn", "docx_sandbox.api:app", "--host", "0.0.0.0", "--port", "8080"]
